---
title: "Project-3-Group-A"
author: "Brant Armstrong, Naman Goel"
date: "2022-11-06"
output: html_document
---
# Necessary Packages
```{r, message = FALSE}
library(tidyverse)
library(caret)
library(corrplot)
library(corrr)
library(psych)
library(rmarkdown)
```
# Reading in Data

```{r}
df <- read_csv("./OnlineNewsPopularity.csv")
#Creating a new variable for to contain data channels and removing the old one.
df <- df %>%
  mutate(data_channel = if_else(
    data_channel_is_bus == 1,
    "Business",
    if_else(
      data_channel_is_entertainment == 1,
      "Entertainment",
      if_else(
        data_channel_is_lifestyle == 1,
        "Lifestyle",
        if_else(
          data_channel_is_socmed == 1,
          "Socmed",
          if_else(data_channel_is_tech == 1, "Tech", "World")
        )
      )
    )
  )) %>% 
  select(-c(url, timedelta, data_channel_is_bus, data_channel_is_entertainment,
            data_channel_is_socmed, data_channel_is_tech, data_channel_is_world,
            data_channel_is_lifestyle)) %>%
  mutate(log_shares = log(shares)) %>%
  select(-shares)
  
#Subsetting to just a single data_channel type
df_filtered <- df %>%
                filter(data_channel == "Lifestyle") 
#Creating the training and test datasets
index_train <- createDataPartition(df_filtered$log_shares, p = .7, list = FALSE )
df_train <- df_filtered[index_train,]
df_test <- df_filtered[-index_train,]

```
# EDA

Calculating the correlation of each predictor variable with the outcome variable `shares` and graphing it.
```{r}
cor_train<- df_train %>%
  correlate() %>%
  focus(log_shares)
paged_table(cor_train)

#Graph of the correlations but it's pretty messy. Might be a way to automate only including the top 10 correlated variables to use later
cor_train %>% 
  mutate(term = factor(term, levels = term[order(log_shares)])) %>%  # Order by correlation strength
  ggplot(aes(x = term, y = log_shares)) +
    geom_bar(stat = "identity") +
    ylab("Correlation with log(Shares)") +
    xlab("Variable") +
  theme(axis.text.x = element_text(angle = 90)) 
```

Principal Components
```{r}
#Removing variables that aren't continuous
df_continuous <- df_train %>%
  select(-c(weekday_is_monday, weekday_is_tuesday, weekday_is_wednesday, weekday_is_thursday,
            weekday_is_friday, weekday_is_saturday, weekday_is_sunday, is_weekend, data_channel,
            n_non_stop_words))
#Excluding shares for creating principal components
df_no_shares <- df_continuous %>%
  select(-log_shares)
#Creating PC's along with center and scaling variables
PCs <- prcomp(df_no_shares, center = TRUE, scale = TRUE)
#Creating screeplots
par(mfrow = c(1,2))
plot(PCs$sdev^2/sum(PCs$sdev^2), xlab = "Principal Component",
ylab = "Proportion of Variance Explained", ylim = c(0, 1), type = 'b')
plot(cumsum(PCs$sdev^2/sum(PCs$sdev^2)), xlab = "Principal Component",
ylab = "Cum. Prop of Variance Explained", ylim = c(0, 1), type = 'b')
#Selecting only the PC's up to a 80% variance explained threshold using caret
PCs_eighty <- preProcess(df_no_shares, method = c("center","scale", "pca"), thresh = .8)
#Creating a data frame with just my PC's and log_shares to use later as a regression
df_PC <- predict(PCs_eighty, newdata = df_no_shares)
df_PC <- df_PC %>%
  bind_cols(log_shares = df_continuous$log_shares)
```

Summary statistics using the `describe` function from the `psych` package sorted by standard deviation.
```{r}
tab <-  describe(df_continuous, fast = TRUE)
#Arranging by Standard Deviation and rounding to two places
table_continuous <- tab %>%
  arrange(desc(sd)) %>%
  modify_if( ~is.numeric(.), ~round(.,2))
#Paged table to allow reader to peruse all variables
paged_table(table_continuous)
```

Summary statistics for each variable categorized by newly created `Day` variable.
```{r}
#Creating a Day variable from the different discrete variables for graphs
categ_day <- df_train %>%
  mutate(day = if_else(
    weekday_is_monday == 1,
    "Monday",
    if_else(
      weekday_is_tuesday == 1,
      "Tuesday",
      if_else(
        weekday_is_wednesday == 1,
        "Wednesday",
        if_else(
          weekday_is_thursday == 1,
          "Thursday",
          if_else(
            weekday_is_friday == 1,
            "Friday",
            if_else(weekday_is_saturday == 1,
                    "Saturday", "Sunday")
          )
        )
      )
    )
  ))
#Box plot of log_shares by day
ggplot(categ_day, aes(x = day, y = log_shares, col = day)) + 
  geom_boxplot(fill="grey") + 
  geom_jitter() + 
  ylab("Log Shares") + 
  xlab("") +
  theme(axis.text.x = element_text(angle = 45)) +
  ggtitle("Boxplot for Log Shares by Day")
```


```{r}

```

